### ISSUE TITLE
How to change the Sender Name?

### ISSUE THREAD

**Issue by KrishnaManohar1997** [sklarsa/django-sendgrid-v5#104]
I want to send a specific Sender Name for the email

Is there any setting using which we can customize it? I have checked in the class _EmailMessage_ it doesn't have any parameter to customize the sender_name or from_name

```
msg = EmailMessage(subject="Test Sender Name", body="Test body for sender name",
            from_email="abc@abc.in",to=["abcgood@gmail.com"])
msg.send()

```
For Instance, I need the sender name as _**Support Bot**_ 

 `from_email` inside **_EmailMessage_** class the from `django.core.mail import EmailMessage`

I have checked the EmailMessage class it doesn't have a parameter to customize the Sender Name.

**Comment by sklarsa** [comment]
We use python's built-in `email.utils.parseaddr` method to parse emails into Name/Address tuples (https://docs.python.org/3/library/email.utils.html#email.utils.parseaddr).  This lib accepts [RFC 2822 formatted](https://datatracker.ietf.org/doc/html/rfc2822.html) email address, like so:
`from_email="John Smith <john.smith@example.org>"`.  

Let me know how this works

**Comment by KrishnaManohar1997** [comment]
Hey, @sklarsa  Thanks for your amazingly immediate response.

The solution is working perfectly, can you also add this to the README.md for other devs to find it easily?

**Comment by sklarsa** [comment]
https://github.com/sklarsa/django-sendgrid-v5/issues/105
