### ISSUE TITLE
what does SENDGRID_ECHO_TO_STDOUT do?

### ISSUE THREAD

**Issue by jamesrobertwilliams** [sklarsa/django-sendgrid-v5#109]
I am confused as to what `SENDGRID_ECHO_TO_STDOUT` actually does. If set to `True` where do my emails go?
I see here: https://simpleit.rocks/python/django/adding-email-to-django-the-easiest-way/
the use of pkg wih the flag set to True - but the author claims it still sends the email? What is the point of this flag then?

Should this flag be set to true or false in production?

thank you for the awesome pkg.

**Comment by sklarsa** [comment]
The flag is primarily used for debugging
