### ISSUE TITLE
Personalizations passed as dictionaries cause AssertionErrors

### ISSUE THREAD

**Issue by alichass** [sklarsa/django-sendgrid-v5#113]
Not sure if this is only happening on python 3.10 and above, but the culprit seems to be the type check on [line 444 in mail.py](https://github.com/sklarsa/django-sendgrid-v5/blob/e631f1a273d35756bde7e02340523dbfd97b56ab/sendgrid_backend/mail.py#L444): `type(personalization) == Dict` seems to evaluate to false even when the personalization instances. 
I believe replacing the check with `isinstance(personalization, Dict)` should do the trick and leave things backwards compatible.
(maybe its worth doing this for [line 447](https://github.com/sklarsa/django-sendgrid-v5/blob/e631f1a273d35756bde7e02340523dbfd97b56ab/sendgrid_backend/mail.py#L447) as well?)

Let me know if it would be helpful for me to make the changes and create a PR.
Thanks!

**Comment by sklarsa** [comment]
Thank you for tracking this down! A PR would be fantastic if you have time

**Comment by sklarsa** [comment]
closed by #114
