### ISSUE TITLE
How to use custom headers or unique args for email tracking?

### ISSUE THREAD

**Issue by hernantz** [sklarsa/django-sendgrid-v5#116]
With the smtp backend, the `X-SMTPAPI` header was used to inject custom tracking metadata for each email. The web api uses a different method for this.

[Here](https://sendgrid.com/blog/smtp-headers-custom-fields-sendgrid-magic/) it is stated that a `headers` key can be used
But [here](https://docs.sendgrid.com/for-developers/sending-email/v3-mail-send-faq#why-did-you-remove-the-x-smtpapi-parameter-can-i-still-change-my-mail-settings-tracking-settings-and-unique-arguments) and [here](https://docs.sendgrid.com/for-developers/sending-email/unique-arguments) it is stated that the `unique_args` key should be used.

What would be the way to do it with `django-sendgrid-v5`?

**Comment by sklarsa** [comment]
That first article is from 2013, so there's a good chance that it's outdated.

If you want to use the unique_args, it looks like you first need to upgrade your API version to `v3`, and then use the [official python client](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/authentication) to send the args to their server.  It looks like twilio is now actively developing [the original sendgrid repo](https://github.com/sendgrid/sendgrid-python), so I'd suggest just using that in this case.

**Comment by hernantz** [comment]
Leaving this for future reference.  Both `custom_args` and `unique_args` serve the same purpose: https://docs.sendgrid.com/for-developers/tracking-events/event#unique-arguments-and-custom-arguments

This snippet works fine and serves the same use case as `unique_args`:
```python
from django.core.mail import EmailMessage

msg = EmailMessage(
  from_email='to@example.com',
  to=['to@example.com'],
  cc=['cc@example.com'],
  bcc=['bcc@example.com'],
)

msg.custom_args = {'arg1': 'value1', 'arg2': 'value2'}
```
