### ISSUE TITLE
Archive? Deprecate? Let's discuss this repo's future...

### ISSUE THREAD

**Issue by sklarsa** [sklarsa/django-sendgrid-v5#117]
With the release of [Twilio's new Sendgrid API v3](https://docs.sendgrid.com/for-developers/sending-email/api-getting-started) (we support v1 & v2), it's getting to be too difficult to maintain compatibility in this library for all of the various python, django, and sendgrid versions.  I've already dropped support for py2, older versions of py3, and old versions of django.

Twilio removed the hyperlink to this repo in their docs, replacing it with their [own official api](https://github.com/sendgrid/sendgrid-python) that appears to be up-to-date and now well-maintained.

Additionally, since the CI runs on travis and I'm unable to log into twilio to create new API accounts (last time I checked), eventually the integration tests will start to fail.

I'll have to think more about the future of this library and what I want to do with it.  I'm happy to maintain it going forward, but I'm definitely not going to be supporting the new API version.

**Comment by sklarsa** [comment]
Thanks for pointing this out! Tbh, I'm not sure how to update those docs since their docs repo has been archived](https://github.com/sendgrid/docs)...

But I'll stick around and try to support this thing as long as people are using it :-)

**Comment by micahjsmith** [comment]
This is a great package that provides more functionality that sendgrid/sengrid-python as it integrates with django and provides a drop-in email backend. It's totally fine for you as a maintainer to stop supporting old versions of python, django, and sendgrid API. Consumers who use old versions should rely on their package manager to install a compatible version with their stack (i.e. an older release of this package). It should be consumers responsibility to upgrade, not your responsiblity as an open source maintainer to support really old versions of things. Thank you for your service!
