### ISSUE TITLE
HTML emails

### ISSUE THREAD

**Issue by epicfaace** [sklarsa/django-sendgrid-v5#12]
How do I use this to send emails with HTML in them? Right now the HTML is getting escaped.

**Comment by sklarsa** [comment]
Can you provide a code example of how you're sending the email?  Also take a look at the django documentation for sending emails with html content: https://docs.djangoproject.com/en/1.11/topics/email/#sending-alternative-content-types

**Comment by epicfaace** [comment]
Oh, I was using the templates for the default PasswordResetView -- and it appears that that view doesn't support HTML-formatted emails. So it isn't a problem with this library -- sorry!
