### ISSUE TITLE
[QUESTION] sendgrid v6 support

### ISSUE THREAD

**Issue by chess-octane** [sklarsa/django-sendgrid-v5#125]
Hey all, thank you for this great library. 

I have a question regarding the support to sendgrid v6.

The setup.py explicitly has the requirement that indicates this library supports `"sendgrid >=5.0.0"`.

There are a few breaking changes from v5 and v6 and I wanted to know if there are any concerns regarding those.

If this library does not officially support v6, should we somehow make it explicit in the setup.py and also through a note in the README?

I'm happy to help you with that, just let me know the official statement from the maintainer.

Thank you

**Comment by chess-octane** [comment]
By reading the code, I could spot references to v6, this tells me this library supports v6.

There's a potential issue when v7 is released, which will make dependants immediately install the latest version without notice.

Thanks.

**Comment by sklarsa** [comment]
Yes, all supported versions can be found in the testing matrix, tox.ini. I haven't used sendgrid in a few years so it's difficult for me to continue supporting newer versions of the API if they introduce significant breaking changes. If v7 doesn't work with this library then I'll cap the version in pipy
