### ISSUE TITLE
Support EU region endpoints

### ISSUE THREAD

**Issue by mikemanger** [sklarsa/django-sendgrid-v5#129]
SendGrid added a separate API for EU servers.

https://www.twilio.com/en-us/blog/send-emails-in-eu

Support was added to the official sendgrid-python library in 6.10 via a `set_sendgrid_data_residency()` method https://github.com/sendgrid/sendgrid-python/pull/1073 (although I think this could be done in earlier versions too by setting the `host` parameter of `SendGridAPIClient`).

To support this I think we'd need a new optional setting, something like `SENDGRID_REGION`

**Comment by sklarsa** [comment]
Do you mind making a PR for this? I've been unable to test this package for a while because I'm no longer a sendgrid/twilio user. I'm happy to help and code review
