### ISSUE TITLE
Send_mail doesn't raise an exception or send emails

### ISSUE THREAD

**Issue by quantran13** [sklarsa/django-sendgrid-v5#13]
Hi,

As the title says, `send_mail` didn't send the emails, but there was no exception raised, and `fail_siliently` is set to its default value, which I believed is `False`.

I have the following settings in `settings.py`:

```
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = '********'
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
```

The code used to send the emails is:

```
username = self.user.username
from_email = username + "@example.com"
recipient_list = [email1, email2, email3]
cc = ['email4@example.com']
subject = "Approved registration"
body = ""

send_mail(subject, body, from_email, recipient_list)
```

I also tried using `EmailMessage`, but it didn't work too:

```
email = EmailMessage(subject, body, from_email, recipient_list, cc=cc)
email.send()
```

I'm quite sure the API key is correct, since I created a new full access API key and it still doesn't work.

**Comment by sklarsa** [comment]
Can you send a sample of the code that you are using to create and send the
email?  Sendgrid's API can be very temperamental when dealing with the
various email configuration options.  The error handling and messaging in
the underlying sendgrid-python library is not very verbose, but I should be
able to figure it out with a code sample.

**Comment by quantran13** [comment]
@sklarsa I just updated the comment above with example code.

**Comment by quantran13** [comment]
@sklarsa Also, the above code worked when I used Django's SMTP settings, i.e setting `EMAIL_HOST`, `EMAIL_PORT`, `EMAIL_HOST_USER` and `EMAIL_HOST_PASSWORD` in `settings.py`

**Comment by quantran13** [comment]
@sklarsa Actually scratch that, I used `self.user.username` to get the username but the authorization stuff is on another branch... Thank you!
