### ISSUE TITLE
HTTP Error 400 Bad Request - how to debug?

### ISSUE THREAD

**Issue by dbinetti** [sklarsa/django-sendgrid-v5#25]
So I might be missing something here, but trying to send an email which appears to be well-formatted returns a generic `400` error.  There is no indication why or how the email send actually failed.  Looking in the SendGrid logs is no help; they show no attempt was made to send at all.

Reverting to the plain-old SMTP server backend sends it off without issue.  So I have no idea what went wrong or how to fix.  thoughts?

**Comment by dbinetti** [comment]
Sorry, traceback might be helpful here...
```
Exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/project/api/tasks.py", line 612, in send_entry
    raise(e)
  File "/app/project/api/tasks.py", line 610, in send_entry
    result = email.send()
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/app/.heroku/python/lib/python3.6/site-packages/sendgrid_backend/mail.py", line 66, in send_messages
    self.sg.client.mail.send.post(request_body=data)
  File "/app/.heroku/python/lib/python3.6/site-packages/python_http_client/client.py", line 227, in http_request
    return Response(self._make_request(opener, request))
  File "/app/.heroku/python/lib/python3.6/site-packages/python_http_client/client.py", line 161, in _make_request
    raise exc
python_http_client.exceptions.BadRequestsError: HTTP Error 400: Bad Request
```

**Comment by sklarsa** [comment]
Unfortunately, the `python_http_client` library obfuscates error messages from the server by wrapping  `HTTPError`s from urllib in its own custom Exception class.  This is a dependency of the sendgrid python library and is out of the scope of this library.

Most likely, your request to the sendgrid API is invalid in some way.  Make sure that the data in your mail object complies with the following specifications from sendgrid's web api documentation https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html.  If you need to dig in further, I would use some sort of a debugger (I like pudb) to step through the code until you get to urllib's exception.  Then, you should be able to read the message back from the server when you inspect the Exception.  In my experience, you should get enough information from that to solve your issue from there.

I'm closing this since there's not much I can do to fix this here, but feel free to post an example of your request to see if I can help

**Comment by dbinetti** [comment]
Thank you for replying.

**Comment by jameschristopher** [comment]
Having this same issue, I copied the request data into Postman, w/credentials, made a request and got an equally unhelpful error message. https://pbs.twimg.com/media/Dj-aKwCVAAAnUkI?format=jpg

**Comment by sklarsa** [comment]
Can you send the contents of your request if possible?

**Comment by jameschristopher** [comment]
```
{"from": {"email": "no-reply@harvust.com"}, "subject": "Harvust Notification", "personalizations": [{"to": [{"email": "myemail@gmail.com"}], "subject": "Harvust Notification", "substitutions": {"body": "sdafads
fds"}}], "content": [{"type": "text/plain", "value": " "}, {"type": "text/html", "value": " "}], "template_id": "d-a0a2f6a20714469cb9555042f412328e", "mail_settings": {"sandbox_mode": {"enable": False}}, "tracking_settings": {"open_tracking": {"enable": True}}}```

**Comment by sklarsa** [comment]
Maybe try removing one of the items in the "content" list?  Also you may
not even need it at all if you're using a template_id (per these docs
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html).

If none of these work, maybe try reaching out on the official sendgrid
project's issues board? https://github.com/sendgrid/sendgrid-python

On Tue, Aug 7, 2018 at 12:59 PM, James Christopher <notifications@github.com

**Comment by jameschristopher** [comment]
I'll keep messing with it, at least having an errror message is better than nothing. Clearly not an issue with this repository. I'll keep this thread updated for anyone else like me who stumbles upon it.

**Comment by jameschristopher** [comment]
SendGrid recently deprecated their old template system and with it the `substitutions` personalization. They replaced it with a new dynamic template system. You can still use the legacy template system with substitutions. This library will probably need an update when SendGrid updates their Python SDK https://github.com/sendgrid/sendgrid-python/issues/591

**Comment by sklarsa** [comment]
ah thanks for the heads-up!
