### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by JoenyBui** [sklarsa/django-sendgrid-v5#38]
How do I add categories to the email?

I tried something like this but no dice.
```python
EmailMessage(subject=subject, body=message, from_email=sender, to=[recipient, ], headers={'categories': 'dev'})
```

Any thoughts?

**Comment by sklarsa** [comment]
Categories should be a property on the mail object (not included in the headers) as per the docs here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

So to use in this library, you would need to do something like this
```
msg = EmailMessage(...)
msg.categories = ['dev`]
```
