### ISSUE TITLE
sending emails to multiple recipients not working

### ISSUE THREAD

**Issue by Fandekasp** [sklarsa/django-sendgrid-v5#40]
I just realize that whenever we send emails to a mailing list as follow:

```py
        # settings.py
        MANAGERS = ['1@example.com', '2@example.com']

        # email.py
        from django.core.mail import send_mail
        from django.conf import settings

        result_managers = send_mail(manager_subject, message,
                                    from_email, settings.MANAGERS,
                                    html_message=manager_message,
                                    fail_silently=False)
```

only one of the recipients in the list will receive the email.  By checking the last 3 days of activity on sendgrid, I see that 3/8th of mails went to `1@example.com` and 5/8th went to `2@example.com`.  Assuming an email is picked randomly from the list :/

This is unfortunately a critical issue. Not sure if it's related to this project SendgridBackend or an issue with the upstream sendgrid service.

Any idea why this bug occurs and if it can be fixed quickly @sklarsa ?

**Comment by sklarsa** [comment]
That seems very strange.  At this level, we add multiple recipients to the `Personalization` object and pass that along to sendgrid (https://github.com/sklarsa/django-sendgrid-v5/blob/master/sendgrid_backend/mail.py#L91), which matches what they have in their API documentation (https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html).

I would take a look at https://github.com/sendgrid/sendgrid-python to see if there are any similar issues.  I can run some tests later today to see if I can repro the behavior.

**Comment by Fandekasp** [comment]
Would really appreciate that. Our temporary solution is to loop through the
recipients of the list and send emails individually (a bit worried that
it'll eat our monthly plan limit).

**Comment by sklarsa** [comment]
I just tested this line and it worked:
`send_mail("Test","Test Content","sender@sender.com",["email1@corp.com","email2@corp.com"],fail_silently=False)` and received the message in both inboxes.  This is running sendgrid_backend==0.6.893 and sendgrid==5.0.0

Perhaps it is something with the `MANAGERS` value in settings.py?

Sorry I can't help any further.  I'm going to close this issue since I can't repro.  I suggest reaching out to sendgrid for further assistance.
