### ISSUE TITLE
missing release notes

### ISSUE THREAD

**Issue by Fandekasp** [sklarsa/django-sendgrid-v5#42]
project got updated to [0.7.0](https://github.com/sklarsa/django-sendgrid-v5/commit/89098b94d45aa9c618a95e0c9e326e2e76e582ea) 6 days ago, but no git tag got created and no releases notes can be found.
What was this upgrade about ? 

Thank you

**Comment by sklarsa** [comment]
It was to publish https://github.com/sklarsa/django-sendgrid-v5/commit/e575431071b5dd76a0ac9df4066acdae82ce84e1 to pypi.

The 0.7 bump was just to clean up the semantic versioning

I'll make a github release now

**Comment by Fandekasp** [comment]
thanks for the fast reply!
