### ISSUE TITLE
Sandbox mode: "Invalid type. Expected: boolean, given: string."

### ISSUE THREAD

**Issue by florimondmanca** [sklarsa/django-sendgrid-v5#43]
## Problem description

Hi,

I was using SendGrid and django-sendgrid-v5 to send email in a Django app. At some point, I stumbled upon a 400 Bad Request error:

```json
{
  "errors": [
    {
      "message": "Invalid type. Expected: boolean, given: string.",
      "field": "mail_settings.sandbox_mode.enable",
      "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.mail_settings.sandbox_mode.enable"
    }
  ]
}
```

Obviously, the `sandbox_mode` was being given a `str` value instead of a `bool`. In this package's source code, this is how it is computed:

```python
# sendgrid_backend/mail.py, SendgridBackend.__init__()
self.sandbox_mode = settings.DEBUG and sandbox_mode_in_debug
```

I noticed that (for some reason) I had set `DEBUG` to be the empty string, `''`. After that, I unset the environment variable so that a default value would be used — `False` (the boolean). Then, all went fine.

The reason why `sandbox_mode` was given a string value in this context is because `'' and False` and `'' and True` both result in `''` (not `False`!) in Python — so `sandbox_mode` was effectively the empty string. Note that this could have occurred for any value of `DEBUG` that is "false-y", such as `0` or `None`.

## Suggestions

This was a rather confusing experience and it seems like something the library code should anticipate. I wanted to discuss how not to have this happen again.

I envision two possible fixes:

1. Add a runtime check when assigning `self.sandbox_mode` to make sure that `sandbox_mode` is assigned a `bool`. If not, raise an `AssertionError` with a helpful message, like so:

```python
assert isinstance(self.sandbox_mode, bool), 'Some helpful message about DEBUG and SENDGRID_SANDBOX_MODE_IN_DEBUG here'
```

This check would be made upon server start-up, so we'd be warned before the app attempts to send any email.

2. Force the conversion of `settings.DEBUG` to a `bool`. After all, the problem here was that I was using a false-y value believing it would be treated as `False`. I would also argue that the same operation should be done on `sandbox_mode_in_debug ` (which may be assigned the value of `SENDGRID_SANDBOX_MODE_IN_DEBUG`) to prevent any issue.

```python
self.sandbox_mode = bool(settings.DEBUG) and bool(sandbox_mode_in_debug)
```

Either (or another) way, I would be happy to provide a PR for this. Glad to discuss further.

**Comment by sklarsa** [comment]
I think this should be checked on app startup, as in your second example.
Want to make a PR?  Thanks for the in-depth report!

**Comment by florimondmanca** [comment]
Done! See #44. I was not exactly sure which solution you referred to, but I implemented the second example.
