### ISSUE TITLE
Question: When is your next release scheduled for?

### ISSUE THREAD

**Issue by whwkong** [sklarsa/django-sendgrid-v5#46]
Hello, I am looking forward to using the `SENDGRID_ECHO_TO_STDOUT` setting in the master branch.  
Do you have any idea when the next release is scheduled?

**Comment by sklarsa** [comment]
I can update pypi in a few minutes...

**Comment by sklarsa** [comment]
https://github.com/sklarsa/django-sendgrid-v5/tree/0.7.1
