### ISSUE TITLE
send_mail fails silently on empty SENDGRID_API_KEY

### ISSUE THREAD

**Issue by whwkong** [sklarsa/django-sendgrid-v5#47]
If my `SENDGRID_API_KEY` is missing or incorrect, `send_mail` fails silently which is somewhat surprising.

**Comment by sklarsa** [comment]
What do your settings look like?  When my `SENDGRID_API_KEY` is missing, I get an ImproperlyConfigured error (https://github.com/sklarsa/django-sendgrid-v5/blob/d754a8891fe18577d3454f146a102038fd43448e/sendgrid_backend/mail.py#L43)

**Comment by sklarsa** [comment]
Closing for now until better repro steps are provided
