### ISSUE TITLE
Unique Arguments "custom_args" is not picked.

### ISSUE THREAD

**Issue by EmadMokhtar** [sklarsa/django-sendgrid-v5#48]
If you try to pass a [unique argument](https://sendgrid.com/docs/for-developers/sending-email/unique-arguments/) "which called `custom_args` in sendgrid APIs" in the message, the Backend won't pick it and assign it to SendGrid APIs.

The solution is to check if there is custom args and them call the APIs to add them.

``` python
    def _build_sg_mail(self, msg):
        ...
        if msg.custom_args:
            for k, v in msg.custom_args.items():
                personalization.add_custom_arg(CustomArg(k, v))
```

**Comment by sklarsa** [comment]
Can you make a PR for this along with a quick unit test? Thanks
