### ISSUE TITLE
Test Sendgrid v6 compatability

### ISSUE THREAD

**Issue by sklarsa** [sklarsa/django-sendgrid-v5#52]
https://github.com/sendgrid/sendgrid-python/releases/tag/v6.0.2

Also consider renaming the project to something more generic

**Comment by RyanNoelk** [comment]
FYI, there is a breaking change in this. You are trying to import `ASM` which has been renamed to `Asm` in Sendgrid 6.
See:
- https://github.com/sklarsa/django-sendgrid-v5/blob/master/sendgrid_backend/mail.py#L18
- https://github.com/sendgrid/sendgrid-python/blob/master/sendgrid/helpers/mail/asm.py#L5

I've restricted the sendgrid dep to `sendgrid==5.6.0` in my requirements file, which makes everything happy again.

Thanks for the project tho :)

**Comment by sklarsa** [comment]
Thanks for the heads up! I figured something would break with this major version change. I’ll try to make this compatible with v5 and v6 since I don’t expect everyone to upgrade immediately

**Comment by thinkingserious** [comment]
Feel free to tag me if you have any questions (I am the maintainer for the sendgrid-python SDK). Thank you!

**Comment by sklarsa** [comment]
Thanks! I have a branch with tests almost passing here
https://github.com/sklarsa/django-sendgrid-v5/pull/53.  I just want some
time to go over the changes to make sure that we don't break any existing
functionality for anyone

**Comment by sklarsa** [comment]
#53
