### ISSUE TITLE
django-allauth compatibility

### ISSUE THREAD

**Issue by KrunchMuffin** [sklarsa/django-sendgrid-v5#57]
So, I can send via manage.py with the following

```
from django.core.mail import send_mail

send_mail(
    'Subject here',
    'Here is the message.',
    'from@example.com',
    ['to@example.com'],
    fail_silently=False,
)
```
but I am not getting emails that would be sent from django-allauth.
Any ideas? I'm it implements the standard send mail.

**Comment by sklarsa** [comment]
Are you running as `DEBUG = True`?  If so, we turned on sendgrid sandbox mode to ensure that test emails don't get sent.  You can turn this off by setting `SENDGRID_SANDBOX_MODE_IN_DEBUG = False`.  You can also set `SENDGRID_ECHO_TO_STDOUT` if you want to send the content of the email to a stream.

**Comment by KrunchMuffin** [comment]
wow, ok, so i have a prod.py settings with debug=false, but in my base.py it had debug=true. so the prod was not overwriting base. Thank you! Spent some time on this. even looked at those files 100 times.
