### ISSUE TITLE
Add support for ganalytics UTM parameters

### ISSUE THREAD

**Issue by jarshwah** [sklarsa/django-sendgrid-v5#58]
It'd be great if there was some kind of support for defining [ganalytics settings](https://sendgrid.com/docs/ui/account-and-settings/tracking/#google-analytics).

I was thinking rather than defining a new SETTING object, you could grab the attribute on the EmailMessage if it exists.

Current method for providing settings: https://github.com/sklarsa/django-sendgrid-v5/blob/187b9b98192bdd9a5d68a1c7ad55a37ca1c3e89a/sendgrid_backend/mail.py#L292

Proposal:

```
msg = EmailMessage( .. )
msg.tracking_settings = TrackingSettings(
    open_tracking=OpenTracking(..),
    ganalytics=Ganalytics(..)
)
```

Then, in `_build_sg_mail`, you'd just check for the attribute and assign it:

```
mail.tracking_settings = getattr(msg, "tracking_settings", None)
```

What do you think?

If you wanted to loosely support most scenarios, you could consider something like getting all custom attributes added to EmailMessage (by diffing the attributes of the msg instance vs a fresh EmailMessage) and graft all extra attributes onto the Mail instance. I haven't thought too hard about this option though.

**Comment by sklarsa** [comment]
Yeah this is an interesting idea.  I'd want to maintain backwards compatibility for the existing features, which would make the implementation a little messy.  I guess I wanted to abstract away all of the various sendgrid class structure at mail creation time, but that leads to the state that we're in now.  I'll think about this over the weekend

**Comment by jarshwah** [comment]
Yup, tricky figuring out what to abstract or adapt :)

For the record, I've subclassed the backend in my project to play with the idea a bit, and it seems to work:

```
class SendgridTrackingBackend(SendgridBackend):
    def _build_sg_mail(self, msg: EmailMessage):
        data = super()._build_sg_mail(msg)
        tracking: Optional[TrackingSettings] = getattr(msg, "tracking_settings", None)
        if tracking:
            data["tracking_settings"] = tracking.get()
        return data
```
