### ISSUE TITLE
Everything works fine but mails don't get delivered

### ISSUE THREAD

**Issue by abedyngash** [sklarsa/django-sendgrid-v5#61]
I'm using this package to send mails in django. Everything works fine but the mail never reaches to the inbox, neither spam. **I've also tried to look for a similar issue on the closed ones but nothing helpful**
Here are my current configurations: 
`.env` file:

`
EMAIL_BACKEND='sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY='SG.the_rest_of_the_api_key'
`

`settings.py` file:

`EMAIL_BACKEND = env('EMAIL_BACKEND')`
`SENDGRID_API_KEY = env('SENDGRID_API_KEY')`
`SENDGRID_SANDBOX_MODE_IN_DEBUG=False`

and my mail function:
`from django.core.mail import send_mail`

`send_mail(
    mail_subject,
    message,
    'noreply.cpsb@nyeri.go.ke',
    [to_email],
    fail_silently=False,
)`

On sending the email, I get no error, but still the mail doesn't get delivered.
What could I be missing?

**Comment by sklarsa** [comment]
Do you have access to your sendgrid dashboard?  I would take a look to see if the messages are making it to sendgrid.  If not, then it could be a logical issue with either how the settings are configured or some other code issue.

At first glance, your settings look ok to me...

**Comment by abedyngash** [comment]
Huh! The problem was I had not done the sender authentication part - Which involves the DNS -CNAME records. Now everything works fine. Apart from the Django password reset.
