### ISSUE TITLE
utf-8 encoding

### ISSUE THREAD

**Issue by UmarFarooq-Ch** [sklarsa/django-sendgrid-v5#66]
When I send an html email using this API, the receiver got email in iso-8859-1 charset
and if I send email with simple SMTP with my gmail credentials, the receiver got email in utf-8 charset

can anyone help to send html email using utf-8 charset

The problem I face with iso-8859-1 encoding is that if the receiver is gmail user then gmail will append this in every email of the receiver
```[Message clipped]  View entire message```

**Comment by sklarsa** [comment]
I haven't seen this before, is it possible that your sendgrid is configured to default to the `iso-8859-1` charset?

**Comment by UmarFarooq-Ch** [comment]
I was not able to find any option to set charset on sendgrid portal. One more thing, the charset remains same i.e. iso-8859-1 either i send with this library or through SMTP

**Comment by sklarsa** [comment]
Maybe this will help you if you haven't already seen this issue: https://github.com/anymail/django-anymail/issues/150
