### ISSUE TITLE
Sending JSON body to SendGrid

### ISSUE THREAD

**Issue by patagoniapy** [sklarsa/django-sendgrid-v5#69]
I have looked for an example of trying to send a JSON body to the SendGrid WebMail API using django-sendgrid-v5 but have had no luck. I am trying to leverage the dynamic template option which I can see was just added to be supported not long ago. I can also see the documentation on `sendgrid-python v6` [here](https://github.com/sendgrid/sendgrid-python/blob/main/use_cases/transactional_templates.md) but I don't see how this connect to django-sendgrid-v5. 

Any help is greatly appreciated, and afterwards I'll be glad to throw some examples together and create a PR to contribute to the documentation.

**Comment by ptsteadman** [comment]
Here's what I did, after the setup in the readme was complete:

```
from django.core.mail import EmailMessage
msg = EmailMessage(
  from_email='noreply@gameconnexion.com',
  to=[user.email],
)
msg.template_id = "your-dynamic-template-id"
msg.dynamic_template_data = {
  "title": foo
}
msg.send(fail_silently=False)
```
