### ISSUE TITLE
sending email from django setup is not working 

### ISSUE THREAD

**Issue by sevmardi** [sklarsa/django-sendgrid-v5#71]
Running django localhost. 
I have the following settings 
```
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
SENDGRID_API_KEY= os.environ.get('SENDGRID_API_KEY')
SENDGRID_SANDBOX_MODE_IN_DEBUG=False
```
`send_mail('test Subject here', 'Here is the message.', 'from_email' , ['email_to_be_sent_to'], fail_silently=False)`

nothing happens. No emails are sent. How can I debug this?

**Comment by sklarsa** [comment]
Do you see the email attempts when you check your sendgrid dashboard?

**Comment by sevmardi** [comment]
yes, nothing being shown there. Are there any ways to debug this more thoroughly? I can't seem to understand this.

**Comment by sevmardi** [comment]
P.S  Sender Authentication is done as well.

**Comment by sklarsa** [comment]
Can you use `pdb` to step through the code? Perhaps in a simple toy script that sends a test email?

**Comment by sevmardi** [comment]
tried the manage.py shell.. not working as well then tried this 

```
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
```

```
        message = Mail(
            from_email='info@xxx.com',
            to_emails='xx@gmail.com',
            subject='Sending with Twilio SendGrid is Fun',
            html_content='<strong>and easy to do anywhere, even with Python</strong>')
        try:
            sg = SendGridAPIClient("APIKEY")
            response = sg.send(message)
            print(response.status_code)
            print(response.body)
            print(response.headers)
        except Exception as e:
            print(e.message)
```

This does seem to work. Emails coming in.

**Comment by sklarsa** [comment]
What about setting `SENDGRID_ECHO_TO_STDOUT=True` and checking if the message hits stdout?

**Comment by sevmardi** [comment]
Yes I tried this setting. I nothing shows up in sdtout.

**Comment by sevmardi** [comment]
https://github.com/sklarsa/django-sendgrid-v5/issues/71#issuecomment-693453294 works for now.
