### ISSUE TITLE
Per-email click tracking settings possible?

### ISSUE THREAD

**Issue by kalatabe** [sklarsa/django-sendgrid-v5#72]
Sendgrid allows per-email settings AKA "filters", for example to [configure click-tracking](https://sendgrid.com/docs/for-developers/sending-email/smtp-filters/#filter-clicktrack)

The changes introduced in 7b1a291f501e33750fa316c8e16fe10bc91a834d take an "all or nothing" approach - based on Django settings, either all emails are tracked, or none of them.

However, a developer may need to enable tracking for some emails and disable it for others. For example, an email notification about a new blog post could use tracking to measure interaction, but a "password reset" email should never have the reset link rewritten.

Message-specific tracking settings could normally be configured by passing the `headers` kwarg to the `EmailMessage` constructor, for example like so:
```python
smtp_headers = {
    "filters": {
    "clicktrack": {
        "settings": {
                "enable": "0"
            }
        },
        "opentrack": {
            "settings": {
                "enable": "0"
            }
        }
    }
}

EmailMessage(
    subject,
    plain_text_body,
    from_email,
    recipient,
    headers={
        'X-SMTPAPI': json.dumps(smtp_headers)
    }
)
```

As far as I can tell, at the moment the library ignores any custom headers passed via the `headers` kwarg of `EmailMessage,__init__`. Tracking settings are controlled entirely by the application's settings module:

```python
track_email = True
if hasattr(settings, "SENDGRID_TRACK_EMAIL_OPENS"):
    track_email = settings.SENDGRID_TRACK_EMAIL_OPENS
self.track_email = track_email

track_clicks_html = True
if hasattr(settings, "SENDGRID_TRACK_CLICKS_HTML"):
    track_clicks_html = settings.SENDGRID_TRACK_CLICKS_HTML

self.track_clicks_html = track_clicks_html

track_clicks_plain = True
if hasattr(settings, "SENDGRID_TRACK_CLICKS_PLAIN"):
    track_clicks_plain = settings.SENDGRID_TRACK_CLICKS_PLAIN

[...]

tracking_settings = TrackingSettings()
tracking_settings.open_tracking = OpenTracking(self.track_email)
tracking_settings.click_tracking = ClickTracking(self.track_clicks_html, self.track_clicks_plain)

mail.tracking_settings = tracking_settings
```

Am I missing something here? Is it actually possible to configure tracking settings at runtime, for each specific email, or is that not supported?

**Comment by sklarsa** [comment]
At the end of the day, we make calls to sendgrid's API.  So if it's possible through an API call, it should be possible in this middleware.  If you want to see this in the middleware, feel free to make a PR and I'll review ASAP.

**Comment by sklarsa** [comment]
Looking at my previous answer, I don't think I actually answered your question.

You should be able to modify the tracking settings on a per-email basis by modifying the `mail` object properties before you call `mail.send`
