### ISSUE TITLE
Cancel ganalytics tracking in links

### ISSUE THREAD

**Issue by oladhari** [sklarsa/django-sendgrid-v5#73]
Is there a way to cancel the ganalytics tracking in my links from settings :
all the links sent in emails are being added with this line:
```
?utm_medium=email&utm_campaign=website&utm_source=sendgrid.com&utm_source=sendgrid.com&utm_medium=email&utm_campaign=website
```
is there any way to cancel this or hide it?
thank you very much for your help

**Comment by sklarsa** [comment]
I need to look into the sendgrid API to see if this option is supported.. if it is, then it shouldn't be a problem.  I'll take a look as soon as I can get to it

**Comment by oladhari** [comment]
> I need to look into the sendgrid API to see if this option is supported.. if it is, then it shouldn't be a problem. I'll take a look as soon as I can get to it

thank you very much for your fast reply

**Comment by oladhari** [comment]
@sklarsa sorry for annoying you. is there any update? if there is anything I can help with, I would like to help

**Comment by sklarsa** [comment]
My apologies, I’ve been away from my computer the past few days. I can look into this tomorrow

**Comment by sklarsa** [comment]
The easiest way to do this is to turn off the tracking settings in the sendgrid dashboard: https://app.sendgrid.com/settings/tracking

I'm not sure if I want to add this option to the library just yet since this is easily configurable in the sendgrid dashboard, and I'm considering a larger refactor of this library to simplify the codebase.

**Comment by oladhari** [comment]
> The easiest way to do this is to turn off the tracking settings in the sendgrid dashboard: https://app.sendgrid.com/settings/tracking
> 
> I'm not sure if I want to add this option to the library just yet since this is easily configurable in the sendgrid dashboard, and I'm considering a larger refactor of this library to simplify the codebase.

thank you very much! luckily I had access to the sendgrid dashboard, I am looking forward to the new release as well, 
I appreciate all your hard work
