### ISSUE TITLE
commas in sender address names raise 400 error from sendgrid api

### ISSUE THREAD

**Issue by bharling** [sklarsa/django-sendgrid-v5#77]
Just hit this issue in production today unfortunately using this library, haven't had time to delve into it properly but will send a PR if I get the time

Steps to reproduce:

```
from dango.core.mail import send_mail
send_mail( "Subject", "Message", "Sender, Some Org <sender@some.org>", ["recipient@example.com"])

{'status_code': 400, 'reason': 'Bad Request', 'body': b'{"errors":[{"message":"The from object must be provided for every email send. It is an object that requires the email parameter, but may also contain a name parameter.  e.g. {\\"email\\" : \\"example@example.com\\"}  or {\\"email\\" : \\"example@example.com\\", \\"name\\" : \\"Example Recipient\\"}.","field":"from.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.from"}]}', 'headers': <http.client.HTTPMessage object at 0x7fa2885b6198>}
```

I guess there is some parsing issue when converting smtp from_email addresses to the sendgrid sender object format?

**Comment by sklarsa** [comment]
Yeah that looks like an API issue. Try sending some test emails using their API directly to repro the error and see what formatting you need to do to the emails in your database

**Comment by bharling** [comment]
Would like to reopen this if possible, sorry for delay in activity - also seeing issues if a user includes `()` in their name (I know this could be considered an edge case but shouldn't crash the library really). I'll try and implement a PR to fix both issues

**Comment by sklarsa** [comment]
Maybe my `stalebot` duration needs to be adjusted too

**Comment by developertom01** [comment]
Any help for this issue

I am encountering the issue now

**Comment by sklarsa** [comment]
I'll take a look at the issue before the new year.. sorry for the delay

**Comment by moducodes** [comment]
Hey @sklarsa . Is there any update on this issue? Facing it right now. Need the from_email to support commas as they're part of the legal names to be used for some of the third parties and cannot be tweaked.
If there's no solution yet, would really appreciate if anyone can help with a workaround which I can implement in the meanwhile. Thanks!

**Comment by sklarsa** [comment]
Can you try to send a test email using sendgrid's python api outside of django (in a small script)?  This way we can diagnose if it's an upstream issue or something specifically related to this repo...

**Comment by alikr123** [comment]
Is there any update on this? @bharling

**Comment by sklarsa** [comment]
Does anyone know where the issues went for the [sendgrid-python[(https://github.com/sendgrid/sendgrid-python) package?  I'm not sure how to open up an issue with Sendgrid, which I believe is the next step to debugging this issue.

**Comment by sklarsa** [comment]
See https://github.com/sklarsa/django-sendgrid-v5/issues/117... I'd recommend using the [official python api](https://github.com/sendgrid/sendgrid-python) now
