### ISSUE TITLE
`set_template_id` is not a method for `Mail`

### ISSUE THREAD

**Issue by yeeland** [sklarsa/django-sendgrid-v5#8]
https://github.com/sklarsa/django-sendgrid-v5/blob/master/sendgrid_backend/mail.py#L99 still makes reference to `set_template_id`, which appears to have been taken out in v4 of `sendgrid-python` (https://github.com/sendgrid/sendgrid-python/commit/3932ac38b3ba422c70db12e9b17cc6f37af4dfe4#diff-8f6b078362cfbc79d2a0f6a3f1914910L109).

**Comment by sklarsa** [comment]
Thanks! I should be able to get to this at some point today or tomorrow
