### ISSUE TITLE
Output email detail to console in sandbox mode

### ISSUE THREAD

**Issue by morugu** [sklarsa/django-sendgrid-v5#80]
To get easier to email debug.
Like a [Django's Console backend](https://docs.djangoproject.com/en/3.1/topics/email/#console-backend)

**Comment by sklarsa** [comment]
What about setting `SENDGRID_ECHO_TO_STDOUT=True` in `settings.py`?  Does that work for you?

**Comment by morugu** [comment]
Thanks, it works for me.
