### ISSUE TITLE
How to add personalization

### ISSUE THREAD

**Issue by jyothisgm** [sklarsa/django-sendgrid-v5#87]
I am unable to add Personalizations through EmailMessage. Please can you post an example on using it like **https://docs.sendgrid.com/for-developers/sending-email/personalizations#sending-a-single-email-to-a-single-recipient-with-multiple-ccs-and-bccs**

**Comment by sklarsa** [comment]
It depends on the specific Personalization that you want to use.  We have some code examples in the README that you can check out.  Is there a missing Personalization feature that this repo doesn't currently support?

**Comment by jyothisgm** [comment]
Hi,
I am trying to have different subject line for different users. Like the below json. I am unable to figure out how to do it using EmailMessageclass
```
"personalizations": [
    {
      "subject": "YOUR SUBJECT LINE GOES HERE",
      "to": [
        {
          "email": "recipient1@example1.com"
        }
      ],
      "from": {
        "email": "sender1@samedomain.com"
      }
    },
    {
      "subject": "YOUR SUBJECT LINE GOES HERE",
      "to": [
        {
          "email": "recipient2@example2.com"
        }
      ],
      "from": {
        "email": "sender2@samedomain.com"
      }
    },
    {
      "subject": "YOUR SUBJECT LINE GOES HERE",
      "to": [
        {
          "email": "recipient3@example3.com"
        }
      ],
      "from": {
        "email": "sender3@samedomain.com"
      }
    }
  ]
```

**Comment by sklarsa** [comment]
Ah I see.  We don't support multiple Personalizations right now, but that's something we can add to a future release.  I'll open up a milestone for v1.1 and add this ticket to it.

**Comment by jyothisgm** [comment]
Thank You.

**Comment by sklarsa** [comment]
bump

**Comment by sklarsa** [comment]
@jyothisgm does [this PR](https://github.com/sklarsa/django-sendgrid-v5/pull/90) address your issue?

**Comment by jyothisgm** [comment]
From what I understand , this is exactly what I am looking for. I home it works as intended as well. Thanks.

**Comment by sklarsa** [comment]
Close by #93
