### ISSUE TITLE
Django 4.x support

### ISSUE THREAD

**Issue by natanlao** [sklarsa/django-sendgrid-v5#99]
Hi! Thanks developing this package. Would you mind cutting a release to push the changes from #96 to PyPI? I'm running into the `providing_args` deprecation that's addressed in that PR.

**Comment by sklarsa** [comment]
https://github.com/sklarsa/django-sendgrid-v5/releases/tag/v1.1.2

**Comment by natanlao** [comment]
Thanks so much!
